services:
  frontend:
    image: ${DOCKER_USERNAME:-amirpliev}/my-app:uma-frontend
    ports:
      - "8200:3000"
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=http://localhost:8202
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8201
    depends_on:
      - pocketbase
      - backend

  pocketbase:
    image: ${DOCKER_USERNAME:-amirpliev}/my-app:uma-pocketbase
    ports:
      - "8202:8080"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}

  backend:
    image: ${DOCKER_USERNAME:-amirpliev}/my-app:uma-backend
    ports:
      - "8201:8000"
    volumes:
      - ./qdrant/collections:/app/qdrant_collections
    environment:
      - POCKETBASE_URL=http://pocketbase:8080
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      - pocketbase
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "8203:6333"
      - "8204:6334"
    volumes:
      - ./qdrant/storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
